### PR TITLE
fix(nav): keyboard nav now skips hidden options #156

### LINKED ISSUE #156: Arrow key navigation is not skipping hidden menu items
## Describe the bug

When using the arrow keys (up/down) to navigate the menu (e.g. in combobox), hidden items are not being skipped. This results in combobox making selections that it should not.

## To Reproduce

1. Go to the airport example on the combobox demo
1. Type the letter a
1. use the arrow keys to navigate up and down the menu
1. See error

## Expected behavior

You should not see skips in the navigation where it looks like you no longer have an "active" menu option.

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #156

## Summary:

`hidden` options were being considered as `interactive` which meant that the keyboard navigation by arrow keys was not skipping them.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

File: src/auro-menu.js [hunk 1]
```diff
@@ -103,7 +103,7 @@ class AuroMenu extends LitElement {
    * @returns {Boolean} Returns true if the option is interactive.
    */
   optionInteractive(option) {
-    return !option.hasAttribute('disabled') && !option.hasAttribute('static');
+    return !option.hasAttribute('hidden') && !option.hasAttribute('disabled') && !option.hasAttribute('static');
```
Comment (blackfalcon) [inline src/auro-menu.js:106]: I am unsure how to actually test this? From the bug description in the issue, I am not seeing a difference between this branch and the demo in the doc site. 

To test, I took `main` of combobox and linked to the working menu branch. 

Also, there should be a new test, or an updated test for this feature.

**Review by blackfalcon — CHANGES_REQUESTED** [review]

File: src/auro-menu.js (hunk 1 above)
Comment (jason-capsule42) [reply src/auro-menu.js:106]: The demo page includes an example labeled "Menu with hidden options". On the doc site you can see it moves 'active' to the hidden option as you move through the list with the arrow keys. In localhost it correctly skips the hidden option.

We didn't previously have a test that covered skipping disabled items either. I added one to cover both hidden and disabled.

**Review by blackfalcon — APPROVED** [review]
