### PR TITLE
fix(value): auro-menu now handles when to call selectByValue #125

### LINKED ISSUE #125: Move triggering of selectByValue into this component
## Describe the bug

This is work necessary for this auro-select bug: https://github.com/AlaskaAirlines/auro-select/issues/69

The problem is that depending on the timing of components loaded auro-select would attempt to use selectByValue before it was ready.

## To Reproduce

1. Go to the auro-select docsite page for the API
1. Look at the `value` attribute example

Notice that the preset value is not showing up in the element.

1. run the main branch of auro-select locally
1. Look at the `value` attribute example

Notice that the preset value does work correctly

## Expected behavior

The preset value should work correctly in deployed environments.

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #125

## Summary:

Changes the use of the `value` attribute. When updated (e.g. by a parent component) menu will execute the selection workflow.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

File: src/auro-menu.js [hunk 1]
```diff
@@ -134,6 +142,10 @@ class AuroMenu extends LitElement {
    * Process actions for making making a menuoption selection.
    */
   makeSelection() {
+    if (!this.items) {
+      this.items = Array.from(this.querySelectorAll('auro-menuoption'));
```
Comment (blackfalcon) [inline src/auro-menu.js:149]: This line is not covered by a test.

File: src/auro-menu.js [hunk 2]
```diff
@@ -278,12 +290,17 @@ class AuroMenu extends LitElement {
...
 
   /**
+   * @private
    * Method to apply `selected` attribute to `menuoption` via `value`.
    * @param {String} value - Must match a unique `menuoption` value.
    */
   selectByValue(value) {
     let valueMatch = false;
 
+    if (!this.items) {
```
Comment (blackfalcon) [inline src/auro-menu.js:317]: There are no tests for the `selectByValue()` function or this new if statement.

File: src/auro-menu.js [hunk 3]
```diff
@@ -58,6 +59,12 @@ class AuroMenu extends LitElement {
     if (changedProperties.has('matchWord')) {
       this.markOptions();
     }
+
+    if (changedProperties.has('value')) {
+      if (this.value && (!this.optionSelected || this.value !== this.optionSelected.value)) {
+        this.selectByValue(this.value);
+      }
```
Comment (blackfalcon) [inline src/auro-menu.js:70]: There is no test for this if statement.

**Review by blackfalcon — CHANGES_REQUESTED** [review]

**Review by blackfalcon — DISMISSED** [review]

**Review by blackfalcon — APPROVED** [review]
