### PR TITLE
fix(style): address issue with duplicate dividers #18

### LINKED ISSUE #18: auro-menu: sub-menu dividers
## Describe the bug

When two sub-menu options rendered sequentially, we render duplicate dividers, also when a sub-menu is the first or last option, we render unnecessary dividers.

## To Reproduce

Create a menu with two sub-menu components

## Expected behavior

A divider should never be the first or last element in the auro-menu, nor should it follow another divider.

### PR DESCRIPTION
**Pull request by ftaylor-alaska**
# Alaska Airlines Pull Request

Cleans up the way dividers are shown for sub-menu options

**Fixes:** #18 

## Type of change:

- [x] Revision of an existing capability

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by blackfalcon — CHANGES_REQUESTED** [review]
Update commit, try, 

```
fix(style): address issue with duplicate dividers #18
```

File: src/auro-sub-menu.js [hunk 1]
```diff
@@ -26,6 +26,12 @@ class AuroSubMenu extends LitElement {
     `;
   }
 
+  firstUpdated() {
```
Comment (blackfalcon) [inline src/auro-sub-menu.js:29]: I feel like this is a UI issue. Can this not be solved with the CSS?

**Review by blackfalcon — CHANGES_REQUESTED** [review]

File: src/auro-sub-menu.js (hunk 1 above)
Comment (ftaylor-alaska) [reply src/auro-sub-menu.js:29]: To re-iterate what this bug is: When a auro-sub-menu is first, last, or following another auro-sub-menu, we have an unwanted divider. These dividers aren't borders on the auro-sub-menu, but instead are divs of their own.

image

Part of the design spec is to have dividers above/below a group of menu options. This divider can't be a border on this parent element because it must be less wide than the containing items. Therefore, there is a separate div (.divider) within the parent (auro-sub-menu). Could you explain how we might conditionally set these inner dividers based on the location of the parent div (auro-sub-menu). I'm trying to think of a clever way to use the pseudo attributes such as first-child etc. to come up with this. In the future it looks like a selector :has could be used but this is not yet available.

Comment (blackfalcon) [reply src/auro-sub-menu.js:29]: Will allow this to merge for now. New issue created for post-merge refactor.
